spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnenglish?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    #   url: jdbc:mysql://localhost:3306/learnenglish
    username: root
    password: MinhTri138
  #    type: com.alibaba.druid.pool.DruidDataSource


  mvc:
    #Sau khi c?u hình nó, không c?n ph?i thay ??i ???ng d?n ?? di chuy?n trang html?
    static-path-pattern: /static/**    #Cách yêu c?u tài nguyên t?nh
  mail:
    host: smtp.qq.com
    username: 412503533@qq.com  # ?i?a chi? email
    password: rkhhvjurvnbtbjje # Mã ?y quy?n
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  thymeleaf:
    cache: false
    check-template-location: on
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/static/


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.springboot.myenglish.entity
  configuration:
    map-underscore-to-camel-case: on #Camel case


# pagehelper pagination
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


