spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studywords?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    #    url: jdbc:mysql://localhost:3306/studywords
    username: root
    password: MinhTri138

