spring:
  datasource:
    url: jdbc:mysql://sql8.freemysqlhosting.net:3306/sql8587252?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: sql8587252
    password: tvtP7bJfT2

  main:
    allow-circular-references: true

  mvc:
    #Sau khi cấu hình nó, không cần phải thay đổi đường dẫn để di chuyển trang html!
    static-path-pattern: /static/**    #Cách yêu cầu tài nguyên tĩnh
    resources:
      static-locations: classpath:/static/  # Vị trí cấu hình của tài nguyên tĩnh, có thể được viết dưới dạng một mảng để định cấu hình nhiều thư mục

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: manh.nv1005@gmail.com
    password: lfzqxmtjtavrtley
    port: '587'

  thymeleaf:
    cache: false
    check-template-location: on
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.group19.learnenglishweb.pojo
  configuration:
    map-underscore-to-camel-case: on #Camel case


# pagehelper pagination
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql